### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by evnvc** [seanblanchfield/seans-homeassistant-addons#4]
Hi and thank you in advance for this great add-on, me and my partner are using it on a daily basis. 
Not really an issue, but a kind request if possible: can we customize the HA card in the front end somewhere in the add-on settings? I would love to remove the Stop Name from being displayed on the card, as I'm using it in conjunction with an expander card. Also because I have two stops named identically around my home and that makes things confusing. Tried to dig into the js file but for some reason I couldn't manage to get rid of it, even if I removed the <h2> block from there.

**Comment by seanblanchfield** [comment]
This wouldn't be too hard to add, but it's also possible to achieve this with [card-mod](https://github.com/thomasloven/lovelace-card-mod).  Here's a screenshot of some additional manual styling added via _card-mod_ that hides the heading:

![image](https://github.com/seanblanchfield/seans-homeassistant-addons/assets/1843797/65f58154-a3a2-4f02-b702-89bc5f7a35ff)

It wouldn't be too hard to add a setting to hide the heading into the custom card as you requested, but if this approach would work for you, then perhaps there's no need.  

BTW, if you're in Dublin, I created this [google group](https://groups.google.com/g/smart-home-dublin) to see if we can gather enough local HA users to do a casual meetup or trade other Ireland-specific smart home tips.

**Comment by evnvc** [comment]
Wow, wasn't aware card mod was even an option! Thank you for the support, will give the yaml method a try (need to step up my card mod game)
